name: robisalesautomation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  flutter_inappwebview: ^6.0.0
  image_picker: ^1.0.7
  geolocator: ^10.1.0
  webview_flutter: ^3.0.0
  percent_indicator: ^4.2.3
  pie_chart: ^5.4.0
  sqflite: ^2.3.1
  dio: ^5.4.0
  path_provider: ^2.1.2
  dropdown_search: ^5.0.6
  dropdown_button2: ^2.3.9
  syncfusion_flutter_datepicker: ^24.2.3
  intl: ^0.19.0
  pdf: ^3.10.7
  url_launcher: ^6.2.4
  google_maps_flutter: ^2.6.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/robilogo.png
    - assets/images/starline.png

